var researchTitles = [
    'What is the perception of aging in different cultures?',
    'Inequality as a social problem',
    'The changes in social interactions associated with aging',
    'Latino youth teen pregnancy',
    'Ambient awareness and its connection to social media',
    'Gender in the 21st century: fighting dangerous stereotypes',
    'The concept of affirmative action',
    'Anti-vaccination as a new viral social movement',
    'non-parental child care',
    'Child abuse as a social issue',
    'What is the social background of a spreading anti-vaccination movement?',
    'Critical race theory: the analysis of the Black Lives Matter activist movement',
    'Underage drinking: trends, impacts, and interventions',
    'What reactions can be observed in response to Black Lives Matter on social media?',
    'Arranged marriages’ advantages and disadvantages',
    'Sociology: class systems and their social rules in different cultures',
    'Parents need help: restricting access to video games',
    'The most apparent clashes between social classes in the world',
    'The phenomena of cliques: a case study of high school students',
    'Social problems of people with disabilities',
    'Criminal organizations: social behavior of cliques in prison',
    'Risk of early pregnancies among Latina teens',
    'What kind of people tend to form cliques in high school?The Me Too movement as an example of conflict theory',
    'The Me Too movement as an example of conflict theory',
    'The drinking age limit',
    'Conflict theory: how to prevent the fight over power in families?',
    'Sexual abuse over children in Philippines',
    'What are the leading root causes of consumerism?',
    'Illegal immigration: impacts on immigrants and countries',
    'Conscious shopping as an opposition of consumerism',
    'Changing gender roles in families',
    'Institutional violence in service providing industry',
    'Institutional violence in healthcare: factors and ways of intervention',
    'The effects of consumerism on environmental sustainability',
    'Capitalist globalization and the ways consumerism supports it',
    'Racism and its effects on our society',
    'Substance abuse: how much is enough?',
    'Immigration to the United States – the DREAM act',
    'Counterculture as a social mainstream: a case study of a specific country',
    'What are the benefits of countercultures for society?',
    'The role of gender in interactions via social media',
    'Theoretical foundation of gender as a culturally-prescribed role',
    'The critical differences between cults and sects',
    'Do cults have anything to do with religion?',
    'Modern issues of gender studies',
    'Effects of poverty on college education in the USA',
    'Is cultural appropriation a negative thing?',
    'Racism in American education',
    'Impacts of social theories on politics as a social institution',
    'Why does cultural appropriation cause political contestations?',
    'Racism and discrimination towards African-Americans',
    'The social effects of cultural assimilation: an overview',
    'Eliminating healthcare disparities in the LGBTQI community',
    'How to differentiate race and ethnicity, and why are these terms so similar?',
    'Can new technology increase the gender pay gap?',
    'Legitimization of prostitution',
    'Sociological perspective: the connection between economic inequality and family issues',
    'Effect of video game violence',
    'Why is being a fan of something more than just being a loyal customer?',
    'Poverty as a social issue',
    'A social study: are fashion trends connected to culture?',
    'Should abortion be legal or illegal?',
    'Fashion as a distraction from important issues for society',
    'Gender identity: promotion of equality for sexual orientation',
    'Collective intelligence: the phenomena of the flocking behavior',
    'Mass media and fear of missing out: Millennials can’t live without updates',
    'The social role of mass media communication',
    'How do people treat their nationality in different countries?',
    'Social issues highlighted by the Occupy movement'
]

function newTitle() {
	var randomTitles = Math.floor(Math.random() * (researchTitles.length));
	document.getElementById('answer').innerHTML = researchTitles[randomTitles];
	document.getElementById('answer').style.background = "#a67c56";
}