var researchTitles = [
    'Is poverty a concern of a corporation?',
    'Labor relations: the latest tendencies and the predictions for the future.',
    'Diversity as a contemporary working reality. ',
    'Personal networking: labor-corporate communication tool.',
    'E-business: the world-wide globalization process. ',
    'Leadership and business in the modern world.',
    'Copyright law: is it on the side of the artist or the company representing them?',
    'Advertisement and consumer behavior.',
    'Apple: how to turn your brand into a religion. ',
    'Word of mouth: a fossil or a gem?',
    'Facebook and business.',
    'Pay for performance: a source of loyalty or displeasure?',
    'Local customization vs. global standardization. ',
    'External recruiting vs. Internal promotions. ',
    'Does a multinational corporation have a motherland?',
    'Management by walking around (MBWA). ',
    'The AIDA formula in advertising.',
    'Free market: an achievable goal or a utopia?',
    'Family business: pros and cons. ',
    'Franchises vs. “from scratch” businesses.',
    'Marijuana business in the US: state law vs. federal law.',
    'Governments vs. private businesses.',
    'The Internet and consumer behavior.',
    'The culture of consumerism. ',
    'The best countries to invest into in 2020.',
    'Outsourcing: its advantages and disadvantages for a business. Is it ethical?',
    'Authors and copyright: which works better, legal names or nom de plumes?',
    'Negotiation tactics: understanding authority.',
    'Oil prices impacts on consumer behavior in Philippines.',
    'Corruption cases: do state officials have a higher chance of succeeding with a request for dismissal?',
    'Juicy Fruit: business strategies and product promotion.',
    'Alcohol: the advantages of the sale and consumption laws for the society’s well-being.',
    'Organizational change capacity concept .',
    'The correlation between wages and employee productivity.',
    'The correlation between strategic management and employee productivity.',
    'Teenagers vs. business: the phenomenon of teenage business.',
    'Small business: the basis of economics.',
    'Crisis management in business.',
    'Negotiation and diplomacy in business.',
    'Brands: what’s their place in the modern market?',
    'Teenagers and brands: what brands are the most popular among modern teenagers?',
    'Mandatory recycling: how would it affect the prices? Would it be cost-effective in the long term?',
    'Advertising in schools: is it acceptable?',
    'Social media: what marketing strategies are used there? Does it influence offline advertisement?',
    'Minimum wage: should it be canceled? Why?',
    'Mobile phones: what has facilitated their high sales rates in recent years?',
    'Brainstorming: how effective is it in producing ideas and business solutions?',
    'Business negotiation: what are the styles of intercultural dialogue?'
]

function newTitle() {
	var randomTitles = Math.floor(Math.random() * (researchTitles.length));
	document.getElementById('answer').innerHTML = researchTitles[randomTitles];
	document.getElementById('answer').style.background = "#a67c56";
}